files:
  - source: /*.*
    ignore:
      - /*.xml
      - Sample.csv
    translation: /Ira_2/%language%.%original_file_name%
    multilingual_spreadsheet: 1
    scheme: 'identifier,source_phrase,context,es-ES,fr,de,sv-SE,uk'
    translation_replace:
      uk: 
-  "source" : "/uk.ini",
   "dest" : "/smth.ini",
   "translation" : "/ira dest/%language%.%original_file_name"
