files:
  - source: /*.*
    ignore:
      - /*.xml
      - Multilingual_spreadsheet_sample.csv
    translation: /Ira_2/%language%.%original_file_name%
    first_line_contains_header: 1
    scheme: 'identifier,context,source_or_translation'
    translation_replace:
      uk: 
