files:
  - source: /olia_test/translations_po/german/*.po
    translation: /olia_test/translations_po/%locale%/%original_file_name%
  - source: /**/*.*
    ignore:
      - /**/*.csv
    translation: /%original_path%/%locale%/%original_file_name%
  - source: /test/fr_FR/*.xml
    translation: /test/%locale%/%original_file_name%.xml
    translate_content: 0
