files:
  - source: /Multilingual_spreadsheet_sample.csv
    translation: /smth/%locale%/%original_file_name%
    scheme: 'identifier,context,source_phrase,es-ES,fr'
    dest: /someotherfolder/ukrn.ini
