files:
  - source: /*.po
    translation: /olia_test/translations_po/%locale%/%original_file_name%
   "language mapping" : {
  "two letters code" : {
     "it" : "itl
      }
    }
    "export languages": [
    "de",
    "it"
    ]
